import sdkConfig from './.genesys/sdk/eslint.config.js';

/**
 * ESLint configuration for this Genesys project.
 *
 * This file imports the SDK's base ESLint configuration and exports it.
 * You can customize/extend the rules here for your specific project needs.
 *
 * @example Add custom rules:
 * export default [
 *   ...sdkConfig,
 *   {
 *     rules: {
 *       'custom/my-rule': 'warn'
 *     }
 *   }
 * ];
 */
export default [
  ...sdkConfig,
  /*
   * src/.virtual-entry.ts is generated by the SDK build, and TypeScript's default include
   * glob does not match dotfiles - so it is not in the tsconfig project, and eslint's
   * type-aware parser errors on it the moment a build happens to leave it on disk. That
   * made `pnpm lint` pass or fail depending on whether the last build had written it yet,
   * which is a check nobody can trust.
   */
  // The editor's minified output is not source and must never be auto-fixed by lint.
  { ignores: ['src/.virtual-entry.ts', '.dist/**'] },
  // Add your custom overrides below:
  // {
  //   rules: {
  //     // your custom rules
  //   }
  // }
];
