// This file is auto-generated by scripts/generate-property-metadata.ts
// Do not edit manually

import { registerGeneratedClassMetadata, registerGeneratedPropertyMetadata } from '@gnsx/genesys.js';

import { ContactScene } from './omniscient/view/ContactScene.js';

export function registerMetadata(): void {
  registerGeneratedPropertyMetadata(ContactScene, {
      "sceneId": {
        "type": "string"
      }
    });

}

// Deferred to avoid circular reference issues during module initialization
queueMicrotask(registerMetadata);
